<style>
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
a { color:#4bac4c; text-decoration:none; transition: background-color 0.4s ease 0s, border 0s ease 0s, color 0.4s ease 0s, opacity 0.4s ease-in-out 0s; }
table {
	border-collapse: collapse;
	border-spacing: 0;
}
.container{width: 100%}
.inner_container{max-width: 1000px; margin: 0 auto;box-sizing: border-box;}

.dashboard_cards{width: 100%;padding: 10px;box-sizing: border-box;}
.dashboard_cards ul li{display: inline-block;width: 18%;margin: 5px;box-sizing: border-box;}
.dashboard_cards ul .bg_one{background-color: #1b80c2;}
.dashboard_cards ul li.bg_one .top_tilte{width: 100%;padding: 10px;box-sizing: border-box;background-color: #328dc8;}
.dashboard_cards ul li.bg_one .top_tilte span{color: #fff;font-size: 15px}
.dashboard_cards ul li.bg_one .img_box{width: 100%; display: inline-block;padding: 10px 20px;box-sizing: border-box;}

.dashboard_cards ul li.bg_one .img_box img{max-width: 50%;float: left;width:85px;height:auto;}
.dashboard_cards ul li.bg_one .img_box span{display: inline-block;float: right;color: #fff;padding-top: 35px;}
.dashboard_cards ul li.bg_one .view_more{padding: 0px 0px}
.dashboard_cards ul li.bg_one .view_more a{color: #fff;font-size: 15px;padding: 10px 10px;display: block;background-color: #1873ae}
.dashboard_cards ul .bg_two{background-color: #f3aa41;}
.dashboard_cards ul li.bg_two .top_tilte{background-color: #f4b354;width: 100%;padding: 10px;box-sizing: border-box;}
.dashboard_cards ul li.bg_two .top_tilte span{color: #fff;font-size: 15px}
.dashboard_cards ul li.bg_two .img_box{width: 100%; display: inline-block;padding: 10px 20px;box-sizing: border-box;}
.dashboard_cards ul li.bg_two .view_more a{background-color: #da993a;color: #fff;font-size: 15px;padding: 10px 10px;display: block;}
.dashboard_cards ul li.bg_two .img_box img{max-width: 50%;float: left;width:85px;height:auto;}
.dashboard_cards ul li.bg_two .img_box span{display: inline-block;float: right;color: #fff;padding-top: 35px;}
.dashboard_cards ul .bg_three{background-color: #77b8d8;}
.dashboard_cards ul li.bg_three .top_tilte{background-color: #85bfdc;width: 100%;padding: 10px;box-sizing: border-box;}
.dashboard_cards ul li.bg_three .top_tilte span{color: #fff;font-size: 15px}
.dashboard_cards ul li.bg_three .img_box{width: 100%; display: inline-block;padding: 10px 20px;box-sizing: border-box;}
.dashboard_cards ul li.bg_three .view_more a{background-color: #6ba5c2;color: #fff;font-size: 15px;padding: 10px 10px;display: block;}
.dashboard_cards ul li.bg_three .img_box img{max-width: 50%;float: left;width:85px;height:auto;}
.dashboard_cards ul li.bg_three .img_box span{display: inline-block;float: right;color: #fff;padding-top: 35px;}
.dashboard_cards ul .bg_four{background-color: #e45847;}
.dashboard_cards ul li.bg_four .top_tilte{background-color: #e7695a;width: 100%;padding: 10px;box-sizing: border-box;}
.dashboard_cards ul li.bg_four .top_tilte span{color: #fff;font-size: 15px}
.dashboard_cards ul li.bg_four .img_box{width: 100%; display: inline-block;padding: 10px 20px;box-sizing: border-box;}
.dashboard_cards ul li.bg_four .view_more a{background-color: #cd4f40;color: #fff;font-size: 15px;padding: 10px 10px;display: block;}
.dashboard_cards ul li.bg_four .img_box img{max-width: 50%;float: left;width:85px;height:auto;}
.dashboard_cards ul li.bg_four .img_box span{display: inline-block;float: right;color: #fff;padding-top: 35px;}
.dashboard_cards ul .bg_five{background-color: #2fc44f;}
.dashboard_cards ul li.bg_five .top_tilte{background-color: #2fc44f;width: 100%;padding: 10px;box-sizing: border-box;}
.dashboard_cards ul li.bg_five .top_tilte span{color: #fff;font-size: 15px}
.dashboard_cards ul li.bg_five .img_box{width: 100%; display: inline-block;padding: 10px 20px;box-sizing: border-box;}
.dashboard_cards ul li.bg_five .view_more a{background-color: #2fc44f;color: #fff;font-size: 15px;padding: 10px 10px;display: block;}
.dashboard_cards ul li.bg_five .img_box img{max-width: 50%;float: left;width:85px;height:auto;}
.dashboard_cards ul li.bg_five .img_box span{display: inline-block;float: right;color: #fff;padding-top: 35px;}
@media (min-width:200px) and (max-width:900px){
	.dashboard_cards ul{text-align: center;}
	.dashboard_cards ul li{width: 45%;margin: 4px;margin-bottom: 8px;}
	
}
@media (min-width:600px) and (max-width:900px){
		.dashboard_cards ul li{width: 31%;margin: 4px;margin-bottom: 8px;}	
}
</style>
<div class="container">
	<div class="inner_container">
        <h1>Delete My Account Statistics</h1>
        <?php if($block->showSelector()): ?>
        <div class="admin-selector" style="width: 100%; align-items: left;">
            <div class="field admin_id">
                <div class="control">
                    <select id="admin_id" name="admin_id" title="<?php /* @escapeNotVerified */ echo __('Select Admin') ?>" class="validate-select" >
                        <option value="all">All</option>
                        <?php $storedValue = $this->getPreSelectedAdmin(); ?>
                        <?php foreach($block->getAllAdmins() as $admins): ?>
                        <?php $selected = $admins['value'] == $storedValue ? 'selected="selected"' : ''; ?>
                        <option <?=__($selected) ?> value="<?= __($admins['value'])?>"><?= __($admins['label'])?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="dashboard_cards">
            <ul>
                <li class="bg_five">
                    <div class="top_tilte">
                        <span>Total No Of Subscription</span>
                    </div>
                    <div class="img_box">
                        <h1><?= __($block->getTotalNoOfSubscription());?></h1>
                    </div>
                    <div class="view_more">
                        <a href="<?= $block->escapeHtml($this->getUrl('outofstocknotification/stock/alert'))?>">View more</a>
                    </div>
                </li>
                <li class="bg_four">
                    <div class="top_tilte">
                        <span>Total No Of Awaiting Notifications</span>
                    </div>
                    <div class="img_box">
                        <h1><?= __($block->getTotalAwatingNotifications());?></h1>
                    </div>
                    <div class="view_more">
                        <a href="<?= $block->escapeHtml($this->getUrl('outofstocknotification/stock/alert'))?>">View more</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>